name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Use Pre-Installed Node.js
      run: |
        nvm use ${{ matrix.node-version }}
        node -v  # Verify the correct Node.js version is used

    - name: Install Dependencies
      run: npm ci