jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
<<<<<<< Updated upstream
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
=======
        node-version: [18, 20]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Node.js Version ${{ matrix.node-version }}
      run: |
        nvm use ${{ matrix.node-version }}
        node -v
>>>>>>> Stashed changes
